<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <artifactId>ordonnance</artifactId>
    <version>1.0-SNAPSHOT</version>
    <packaging>pom</packaging>

    <parent>
        <groupId>fr.cnamts.cpam33</groupId>
        <artifactId>cpam33-parent</artifactId>
        <version>1.0.0</version>
        <relativePath/>
    </parent>

    <modules>
        <module>ordonnance-domain</module>
        <module>ordonnance-application</module>
        <module>ordonnance-infrastructure</module>
        <module>ordonnance-architecture-validation</module>
        <module>ordonnance-db-migrator</module>
    </modules>

    <properties>
        <sonar.coverage.jacoco.xmlReportPaths>${project.basedir}/target/site/jacoco-aggregate/jacoco.xml</sonar.coverage.jacoco.xmlReportPaths>
        <sonar.coverage.exclusions>ordonnance-architecture-validation/**</sonar.coverage.exclusions>
    </properties>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <executions>
                    <execution>
                        <id>report-aggregate</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>report-aggregate</goal>
                        </goals>
                        <inherited>false</inherited>
                        <configuration>
                            <outputDirectory>${project.build.directory}/site/jacoco-aggregate</outputDirectory>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>