# Sources
sonar.sources=ordonnance-application/src/main/java,ordonnance-domain/src/main/java,ordonnance-infrastructure/src/main/java
# Tests (PAS ".")
sonar.tests=ordonnance-application/src/test/java,ordonnance-domain/src/test/java,ordonnance-infrastructure/src/test/java
# Inclusions tests
sonar.test.inclusions=**/*Test.java,**/*IT.java,**/*TI.java
# Exclusions globales (évite les fantômes)
sonar.exclusions=**/target/**,traces/**
# Binaries (OK comme tu l'avais)
sonar.java.binaries=ordonnance-application/target/classes,ordonnance-domain/target/classes,ordonnance-infrastructure/target/classes
# JaCoCo
sonar.coverage.jacoco.xmlReportPaths=ordonnance-application/target/site/jacoco/jacoco.xml,ordonnance-domain/target/site/jacoco/jacoco.xml,ordonnance-infrastructure/target/site/jacoco/jacoco.xml
# Ignore S100 pour tests (corrige aussi l'incohérence IT/TI)
sonar.issue.ignore.multicriteria=e1
sonar.issue.ignore.multicriteria.e1.ruleKey=java:S100
sonar.issue.ignore.multicriteria.e1.resourceKey=**/*Test.java,**/*IT.java,**/*TI.java