
    create table error_catalog (
        active boolean not null,
        http_status integer not null,
        bounded_context varchar(100) not null,
        code varchar(150) not null,
        description varchar(255),
        message varchar(255) not null,
        primary key (code)
    );

    create table medecin (
        id bigint generated by default as identity,
        external_id varchar(255) not null unique,
        nom varchar(255),
        prenom varchar(255),
        rpps varchar(255) not null unique,
        primary key (id)
    );

    create table ordonnance (
        id bigint generated by default as identity,
        medecin_id bigint,
        patient_id bigint not null,
        numero varchar(255) not null,
        primary key (id)
    );

    create table patient (
        date_naissance date,
        id bigint generated by default as identity,
        external_id varchar(255) unique,
        nom varchar(255),
        patient_id varchar(255) not null unique,
        prenom varchar(255),
        primary key (id)
    );

    create table prescription (
        id bigint generated by default as identity,
        ordonnance_id bigint not null,
        medicament varchar(255),
        primary key (id)
    );

    alter table if exists ordonnance 
       add constraint FKm1dn0w5n63jmjmxx25raq4xxq 
       foreign key (medecin_id) 
       references medecin;

    alter table if exists ordonnance 
       add constraint FKpyrgsls35n0ttep37dwdyhv85 
       foreign key (patient_id) 
       references patient;

    alter table if exists prescription 
       add constraint FK9cy9p9or393kjceyhkna3jw2t 
       foreign key (ordonnance_id) 
       references ordonnance;

    create table error_catalog (
        active boolean not null,
        http_status integer not null,
        bounded_context varchar(100) not null,
        code varchar(150) not null,
        description varchar(255),
        message varchar(255) not null,
        primary key (code)
    );

    create table medecin (
        id bigint generated by default as identity,
        external_id varchar(255) not null unique,
        nom varchar(255),
        prenom varchar(255),
        rpps varchar(255) not null unique,
        primary key (id)
    );

    create table ordonnance (
        id bigint generated by default as identity,
        medecin_id bigint,
        patient_id bigint not null,
        numero varchar(255) not null,
        primary key (id)
    );

    create table patient (
        date_naissance date,
        id bigint generated by default as identity,
        external_id varchar(255) unique,
        nom varchar(255),
        patient_id varchar(255) not null unique,
        prenom varchar(255),
        primary key (id)
    );

    create table prescription (
        id bigint generated by default as identity,
        ordonnance_id bigint not null,
        medicament varchar(255),
        primary key (id)
    );

    alter table if exists ordonnance 
       add constraint FKm1dn0w5n63jmjmxx25raq4xxq 
       foreign key (medecin_id) 
       references medecin;

    alter table if exists ordonnance 
       add constraint FKpyrgsls35n0ttep37dwdyhv85 
       foreign key (patient_id) 
       references patient;

    alter table if exists prescription 
       add constraint FK9cy9p9or393kjceyhkna3jw2t 
       foreign key (ordonnance_id) 
       references ordonnance;

    create table medecin (
        id bigint generated by default as identity,
        external_id varchar(255) not null unique,
        nom varchar(255),
        prenom varchar(255),
        rpps varchar(255) not null unique,
        primary key (id)
    );

    create table ordonnance (
        id bigint generated by default as identity,
        medecin_id bigint,
        patient_id bigint not null,
        numero varchar(255) not null,
        primary key (id)
    );

    create table patient (
        date_naissance date,
        id bigint generated by default as identity,
        external_id varchar(255) unique,
        nom varchar(255),
        patient_id varchar(255) not null unique,
        prenom varchar(255),
        primary key (id)
    );

    create table prescription (
        id bigint generated by default as identity,
        ordonnance_id bigint not null,
        medicament varchar(255),
        primary key (id)
    );

    alter table if exists ordonnance 
       add constraint FKm1dn0w5n63jmjmxx25raq4xxq 
       foreign key (medecin_id) 
       references medecin;

    alter table if exists ordonnance 
       add constraint FKpyrgsls35n0ttep37dwdyhv85 
       foreign key (patient_id) 
       references patient;

    alter table if exists prescription 
       add constraint FK9cy9p9or393kjceyhkna3jw2t 
       foreign key (ordonnance_id) 
       references ordonnance;

    create table error_catalog (
        active boolean not null,
        http_status integer not null,
        bounded_context varchar(100) not null,
        code varchar(150) not null,
        description varchar(255),
        message varchar(255) not null,
        primary key (code)
    );

    create table medecin (
        id bigint generated by default as identity,
        external_id varchar(255) not null unique,
        nom varchar(255),
        prenom varchar(255),
        rpps varchar(255) not null unique,
        primary key (id)
    );

    create table ordonnance (
        id bigint generated by default as identity,
        medecin_id bigint,
        patient_id bigint not null,
        numero varchar(255) not null,
        primary key (id)
    );

    create table patient (
        date_naissance date,
        id bigint generated by default as identity,
        external_id varchar(255) unique,
        nom varchar(255),
        patient_id varchar(255) not null unique,
        prenom varchar(255),
        primary key (id)
    );

    create table prescription (
        id bigint generated by default as identity,
        ordonnance_id bigint not null,
        medicament varchar(255),
        primary key (id)
    );

    alter table if exists ordonnance 
       add constraint FKm1dn0w5n63jmjmxx25raq4xxq 
       foreign key (medecin_id) 
       references medecin;

    alter table if exists ordonnance 
       add constraint FKpyrgsls35n0ttep37dwdyhv85 
       foreign key (patient_id) 
       references patient;

    alter table if exists prescription 
       add constraint FK9cy9p9or393kjceyhkna3jw2t 
       foreign key (ordonnance_id) 
       references ordonnance;
