# ===============================
# Datasource POSTGRESQL
# ===============================
spring.datasource.ordonnances.hikari.jdbc-url=jdbc:postgresql://localhost:5432/ordonnance_db
spring.datasource.ordonnances.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.ordonnances.hikari.username=postgres
spring.datasource.ordonnances.hikari.password=${DB_PASSWORD:123456789}
spring.datasource.ordonnances.hikari.maximum-pool-size=48
spring.datasource.ordonnances.hikari.pool-name=ordonnance-pool

spring.datasource.traces.hikari.jdbc-url=jdbc:postgresql://localhost:5431/trace_db?reWriteBatchedInserts=true
spring.datasource.traces.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.traces.hikari.username=postgres
spring.datasource.traces.hikari.password=${DB_PASSWORD:123456789}
spring.datasource.traces.hikari.maximum-pool-size=4
spring.datasource.traces.hikari.minimum-idle=0
spring.datasource.traces.hikari.pool-name=trace-pool

spring.datasource.thesorimed.hikari.jdbc-url=jdbc:postgresql://localhost:5430/thesorimed_db
spring.datasource.thesorimed.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.thesorimed.hikari.username=postgres
spring.datasource.thesorimed.hikari.password=${DB_PASSWORD:123456789}
spring.datasource.thesorimed.hikari.maximum-pool-size=48
spring.datasource.thesorimed.hikari.pool-name=thesorimed-pool
spring.datasource.thesorimed.hikari.read-only=true

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.show-sql=false
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# JPA per-PU (custom)
# ===============================

# ordonnancePU
ordonnance.jpa.packages=fr.cnamts.cpam33.ordonnance.infrastructure.out.entities.ordonnances
ordonnance.jpa.persistence-unit=ordonnancePU
ordonnance.jpa.properties.hibernate.hbm2ddl.auto=create-drop
ordonnance.jpa.properties.hibernate.show_sql=true
ordonnance.jpa.properties.hibernate.format_sql=true
ordonnance.jpa.properties.jakarta.persistence.schema-generation.database.action=drop-and-create
ordonnance.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
ordonnance.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=C:/DATA/prescription/configuration/postgresql/ordonnances/create.sql
ordonnance.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=C:/DATA/prescription/configuration/postgresql/ordonnances/drop.sql
ordonnance.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
ordonnance.jpa.properties.jakarta.persistence.schema-generation.drop-source=metadata

# tracePU
trace.jpa.packages=fr.cnamts.cpam33.ordonnance.infrastructure.out.entities.traces
trace.jpa.persistence-unit=tracePU
trace.jpa.properties.hibernate.jdbc.batch_size=500
trace.jpa.properties.hibernate.order_inserts=true
trace.jpa.properties.hibernate.hbm2ddl.auto=create-drop
trace.jpa.properties.hibernate.show_sql=true
trace.jpa.properties.hibernate.format_sql=true
trace.jpa.properties.jakarta.persistence.schema-generation.database.action=drop-and-create
trace.jpa.properties.jakarta.persistence.schema-generation.scripts.action=drop-and-create
trace.jpa.properties.jakarta.persistence.schema-generation.scripts.create-target=C:/DATA/prescription/configuration/postgresql/traces/create.sql
trace.jpa.properties.jakarta.persistence.schema-generation.scripts.drop-target=C:/DATA/prescription/configuration/postgresql/traces/drop.sql
trace.jpa.properties.jakarta.persistence.schema-generation.create-source=metadata
trace.jpa.properties.jakarta.persistence.schema-generation.drop-source=metadata


# thesorimedPU
thesorimed.jpa.packages=fr.cnamts.cpam33.thesorimed.infrastructure.out.entities.thesorimed
thesorimed.jpa.persistence-unit=thesorimedPU
thesorimed.jpa.properties.hibernate.hbm2ddl.auto=none
thesorimed.jpa.properties.hibernate.connection.provider_disables_autocommit=true

# ===============================
# Flyway
# ===============================
spring.flyway.enabled=false
flyway.ordonnance.enabled=false
flyway.ordonnance.locations=filesystem:C:/DATA/prescription/configuration/postgresql/ordonnances/db/migration
flyway.ordonnance.baseline-on-migrate=true
flyway.ordonnance.baseline-version=1.0
flyway.trace.enabled=false
flyway.trace.locations=filesystem:C:/DATA/prescription/configuration/postgresql/traces/db/migration
flyway.trace.baseline-on-migrate=true
flyway.trace.baseline-version=1.0

# ===============================
# OpenBao
# ===============================
vault.openbao.enabled=false
vault.openbao.uri=http://localhost:1337
vault.openbao.token={$TOKEN_OPEN_BAO:dev-token-open-bao-mock-123}
vault.openbao.namespace=/cpam33
vault.openbao.ordonnance.path=/ordonnances
vault.openbao.trace.path=/traces

# ===============================
# Spring Core / Server
# ===============================
server.timezone=Europe/Paris
spring.main.banner-mode="off"

# ===============================
# Ordonnance
# ===============================
ordonnance.repositories.editique=/srv/

# Technologie de cache (none, inmemory, ignite)
ordonnance.cache.type=none

# === Loaders et configuration du delay de databouncing
ordonnance.loaders.core_pool_size=1
ordonnance.loaders.errors.reload-delay=5000
ordonnance.loaders.errors.file=file:C:\\DATA\\prescription\\ordonnance-infrastructure\\src\\main\\resources\\errors.json
ordonnance.loaders.errors.watcher.enabled=true
ordonnance.loaders.actesMetiers.reload-delay=5000
ordonnance.loaders.actesMetiers.file=file:C:\\DATA\\prescription\\ordonnance-infrastructure\\src\\main\\resources\\actes_metiers.json
ordonnance.loaders.actesMetiers.watcher.enabled=true

# === Writer + Queue de traitement des Traces
ordonnance.traces.writer.workers=2
ordonnance.traces.writer.restart-delay=2s
ordonnance.traces.writer.queue-capacity=50000
ordonnance.traces.writer.batch-size=500
ordonnance.traces.writer.flush-interval=50ms
ordonnance.traces.enqueue-executor.core-pool-size=2
ordonnance.traces.enqueue-executor.max-pool-size=4
ordonnance.traces.enqueue-executor.queue-capacity=20000
ordonnance.traces.enqueue-executor.thread-name-prefix=trace-enq-
ordonnance.traces.enqueue-executor.wait-for-tasks-to-complete-on-shutdown=false

# ===============================
# API Externe
# ===============================
patient.api.url=http://localhost:8081/sages2-web-local/api-externe/v1/consultants
medecin.api.url=http://localhost:8081/sages2-web-local/api-externe/v1/medecins

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,error-catalog-watcher, metrics, prometheus, flyway
management.metrics.export.prometheus.enabled=true
management.endpoint.flyway.enabled=true

# ===============================
# Logging
# ===============================
logging.level.org.flywaydb=DEBUG