# ===============================
# Datasource POSTGRESQL
# ===============================
spring.datasource.ordonnances.hikari.jdbc-url=jdbc:postgresql://localhost:5432/ordonnance_db
spring.datasource.ordonnances.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.ordonnances.hikari.username=postgres
spring.datasource.ordonnances.hikari.password=${DB_PASSWORD:123456789}

spring.datasource.traces.hikari.jdbc-url=jdbc:postgresql://localhost:5431/trace_db
spring.datasource.traces.hikari.driver-class-name=org.postgresql.Driver
spring.datasource.traces.hikari.username=postgres
spring.datasource.traces.hikari.password=${DB_PASSWORD:123456789}

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ===============================
# Ordonnance
# ===============================
ordonnance.repositories.editique=/srv/

ordonnance.loaders.errors.reload-delay=5000
ordonnance.loaders.errors.file=file:D:\\DATA\\ordonnance\\ordonnance-infrastructure\\src\\main\\resources\\errors.json
ordonnance.loaders.errors.watcher.enabled=true

ordonnance.loaders.actesMetiers.reload-delay=5000
ordonnance.loaders.actesMetiers.file=file:D:\\DATA\\ordonnance\\ordonnance-infrastructure\\src\\main\\resources\\actes_metiers.json
ordonnance.loaders.actesMetiers.watcher.enabled=true

ordonnance.loaders.fonctions.reload-delay=5000
ordonnance.loaders.fonctions.file=file:D:\\DATA\\ordonnance\\ordonnance-infrastructure\\src\\main\\resources\\fonctions.json
ordonnance.loaders.fonctions.watcher.enabled=true

# ===============================
# API Externe
# ===============================
patient.api.url=http://localhost:8081/sages2-web-local/api/v1/consultants
medecin.api.url=http://localhost:8081/sages2-web-local/api/v1/medecins

# ===============================
# Actuator
# ===============================
management.endpoints.web.exposure.include=health,info,error-catalog-watcher, metrics, prometheus
management.metrics.export.prometheus.enabled=true