create table acte_metier
(
    fonction_id  bigint       not null,
    code         varchar(255) not null,
    objet_metier varchar(255) not null,
    primary key (code)
);

create table fonction
(
    id          bigint generated by default as identity,
    code        varchar(255),
    description varchar(255) not null,
    primary key (id)
);

create table trace
(
    created_on     timestamp(6) not null,
    id             bigint generated by default as identity,
    acte_metier_id varchar(255) not null,
    medecin_id     varchar(255) not null,
    context        jsonb        not null,
    primary key (id)
);

alter table if exists acte_metier
    add constraint FKh0tv40ho305j1rsrenubhyiai
    foreign key (fonction_id)
    references fonction;

alter table if exists trace
    add constraint FKd7gkt2p4sdhyev24tec9u7mc3
    foreign key (acte_metier_id)
    references acte_metier;
