package fr.cnamts.cpam33.ordonnance.domain.abstracts.exceptions.enums;

import fr.cnamts.cpam33.ordonnance.domain.abstracts.exceptions.ExceptionCode;

public enum OrdonnanceExceptionCode implements ExceptionCode {

    BS_ORDONNANCE_ID_MISSING,
    BS_ORDONNANCE_ID_NUMERIC,
    BS_ORDONNANCE_PATIENT_MISSING,
    BS_ORDONNANCE_MEDECIN_MISSING,

    BS_ORDONNANCE_PRESCRIPTION_MISSING,
    BS_ORDONNANCE_PRESCRIPTION_NOT_FOUND,
    BS_ORDONNANCE_PRESCRIPTION_DUPLICATE,

    BS_ORDONNANCE_IMMUTABLE_WHEN_SIGNED,
    BS_ORDONNANCE_ALREADY_SIGNED,
    BS_ORDONNANCE_SNAPSHOT_MUST_BE_SIGNED,

    BS_ORDONNANCE_SNAPSHOT_GENERATION_ERROR

}
